title: nettlesum
email: 
description: >- 
  Welcome to yet another node in the vast network of prison cells that we call the internet.
baseurl: "" 
url: "https://nettlesum.github.io" 
twitter_username: nettlesum
github_username:  nettlesum
footer: 'This site is powered by <a href=https://jekyllrb.com/>Jekyll</a>, and uses the <a href=https://github.com/mmistakes/minimal-mistakes>minimal-mistakes</a> theme.'
header_pages:
  - index.markdown
  - about.markdown

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
