title: nettlesum
author: 
  name: nettlesum
  email: NULL
description: 
show_excerpts: true

# Date format
minima:
  date_format: "%Y-%m-%d %H:%M"

  # generate social links in footer
  social_links:
    twitter: nettlesum
    github:  nettlesum

header_pages:
 - about.md
 - index.md

# Build settings
remote_theme: no-style-please

plugins:
 - jekyll-feed
 - jekyll-seo-tag
