title: nettlesum
description: time moves in one direction, memory in another.
url: https://nettlesum.github.io
baseurl: 

# footer
footer:
  credit: false
  custom: true

footer_custom: 'This site is powered by Jekyll, running the <a href="https://github.com/oinam/oinam-jekyll">Oinam</a> theme.'

remote_theme: oinam/oinam-jekyll
layout:
  theme: nord
  theme_highlighter: nord
  theme_switch: true
  home_posts_no: 6
  home_postheader_title: 'Recent posts'
  home_postmeta_title: 'View all'
  posts_home: /blog/
  link_new_tab: true # should external links open in a new tab (true) or in the current tab (false)

# styles
# include only the styles you want [true | false]
styles:
  font_family: sans
  forms: true
  syntax_highlighter: true
  
markdown: kramdown
highlighter: rouge

permalink: pretty
permalink: /:title/

sass:
  style: compressed
  sourcemap: never

plugins:
 - jekyll-optional-front-matter
 - jekyll-titles-from-headings
 - jekyll-remote-theme

defaults:
  - scope:
      path: '_posts'
      type: 'posts'
    values:
      layout: 'post'
      permalink: '/:year/:title/'

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - LICENSE
  - netlify.toml
  - node_modules/
  - oinam-jekyll-*.*
  - oinam-jekyll.gemspec
  - README.*
  - server
  - vendor/
  
  - name: Jekyll Deploy Action
  uses: jeffreytse/jekyll-deploy-action@v0.4.0

