title: nettlesum
email: 
description: >- 
  Welcome to yet another node in the vast network of prison cells that we call the internet.
baseurl: "" 
url: "https://nettlesum.github.io" 
twitter_username: nettlesum
github_username:  nettlesum
footer: 'This sites theme is a fork of <a href=https://github.com/b2a3e8/jekyll-theme-console>b2a3e8/jekyll-theme-console</a>.'
header_pages:
  - index.markdown
  - about.markdown

# Build settings
remote_theme: nettlesum/jekyll-theme-console
style: light 
plugins:
  - jekyll-feed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
